name: Operator Release Publish

on:
  push:
    tags:
      - '*'

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: GoReleaser Action
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: release --clean
        env:
          GORELEASER_CURRENT_TAG: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Installer YAML
        run: make build-installer IMG=ghcr.io/sijoma/single-zone-mutator:${{ github.ref_name }}

      - name: Add to Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/install.yaml
          tag_name: ${{ github.ref_name }}
